Areas/Hub/Pages/Events/Edit.cshtml.cs
using LetsGame.Data;
using Microsoft.AspNetCore.Identity;
using LetsGame.Areas.Identity.Data;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using LetsGame.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Primitives;

namespace LetsGame.Areas.Hub.Pages.Events
{
    public class EditModel : PageModel
    {
        private readonly ILetsGame_EventManager _eventManager;
        private readonly UserManager<LetsGame_User> _userManager;

        public EditModel(ILetsGame_EventManager eventManager, UserManager<LetsGame_User> userManager) {
            _eventManager = eventManager;
            _userManager = userManager;
        }

        public string StatusMessage { get; set; } = "";
        public string ReturnURL { get; set; }

        [BindProperty]
        public LetsGame_Event Event { get; set; }
        public bool IsCreate { get; set; }

		public async Task<IActionResult> OnGetAsync(long? eventID, string returnUrl) {
            ReturnURL = returnUrl;
            var user = _userManager.GetUserId(User);
            if (eventID == 0) {
                IsCreate = true;
                Event = new LetsGame_Event();
            } else {
                IsCreate = false;
				var result = await _eventManager.GetUserEventAsync((long)eventID,user);
                Event = result.Event;
			}

            if (Event == null) Redirect(returnUrl);

			return Page();
		}

        public async Task<IActionResult> OnPostAsync(bool isCreate, string? returnUrl) {
            var user = _userManager.GetUserId(User);
            if (!ModelState.IsValid) {
                StatusMessage = "Error: Model Invalid, Please try again";
                return Page();
            }

            if (isCreate) {
                await _eventManager.CreateEventAsync(Event,user);
			}
            else {
                _eventManager.UpdateEvent(Event);
            }

            await _eventManager.SaveAsync();

            if (returnUrl == null) return Redirect("/Hub/Events");
            return Redirect(returnUrl);
		}

        public IActionResult OnPostCancel(string? returnUrl) {
			return Redirect(returnUrl);
		}
	}
}

Areas/Hub/Pages/Events/Index.cshtml.cs
using LetsGame.Areas.Hub.Models;
using LetsGame.Areas.Identity.Data;
using LetsGame.Data;
using LetsGame.Data.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using LetsGame.Services;

namespace LetsGame.Areas.Hub.Pages
{
    [Authorize]
    public class EventModel : PageModel
    {
        //CONSTRUCTOR
        public EventModel(ILetsGame_EventManager eventManager, 
                          UserManager<LetsGame_User> userManager,
                          IFriendsService friendsManager) 
        {
            _eventManager = eventManager;
            _userManager = userManager;
            _friendsManager = friendsManager;
        }

		//MANAGERS
		private readonly ILetsGame_EventManager _eventManager;
		private readonly UserManager<LetsGame_User> _userManager;
        private readonly IFriendsService _friendsManager;

		//DATA
		/// <summary>
		///     A message that is displayed by the status message partial of the current page
		/// </summary>
		public string StatusMessage { get; set; }
		public UserEventsData PageData { get; private set; }
        public string EventName { get; set; }

        //GET
        public async Task<IActionResult> OnGetAsync(long? eventID) {

            var user = await _userManager.GetUserAsync(User);

			if (user == null) {
				return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
			}

            var success = await LoadDataAsync(user.Id,eventID);

			//needs to change at some point
			if (!success) {
				return Redirect("./Index");
			}

            EventName = PageData.GetName();

			return Page();
        }

        //LOADING
        private async Task<bool> LoadDataAsync(string userId, long? eventID) {

            PageData = new UserEventsData(_eventManager);
            var user = await _userManager.GetUserAsync(User);

            var success = await PageData.LoadData(user, eventID, Request.Path);

            if (PageData.IsValid && success) {
                return true;
            } else {
                StatusMessage = "Error: No event data could be loaded";
                return false;
            }
        }

        //PAGE HANDLERS
        public IActionResult OnPostTogglePinned(long eventID, string returnUrl) {
            if (_eventManager.PinEvent(eventID,_userManager.GetUserId(User),out bool IsPinned))
                Debug.WriteLine($"Event: {eventID} {(IsPinned ? "pinned" : "unpinned")} = {IsPinned}.");
            else
                Debug.WriteLine($"Event: {eventID} not found.");
            _eventManager.Save();
            return Redirect(returnUrl);
		}
        public IActionResult OnPostToggledPinnedAjax(long eventID) {

			if (_eventManager.PinEvent(eventID,_userManager.GetUserId(User),out bool IsPinned))
				Debug.WriteLine($"Event: {eventID} {(IsPinned ? "pinned" : "unpinned")} = {IsPinned}.");
			else {
				Debug.WriteLine($"Event: {eventID} not found.");
                return BadRequest();
			}

			_eventManager.Save();

            return new JsonResult(IsPinned);
        }
		public async Task<IActionResult> OnPostDeletePoll(long pollID,string returnUrl) {
			LetsGame_Poll Poll = await _eventManager.GetPollAsync(pollID);

			if (!_eventManager.DeletePoll(Poll)) {
				return Redirect(returnUrl);
			}

			await _eventManager.SaveAsync();

			return Redirect(returnUrl);
		}
		public async Task<IActionResult> OnPostDeleteEvent(long eventID,string returnUrl) {
			var user = _userManager.GetUserId(User);

			if (!_eventManager.DeleteEvent(eventID,user)) {
				return Redirect(returnUrl);
			}

			await _eventManager.SaveAsync();

			return Redirect(returnUrl);
		}
		public async Task<PartialViewResult> OnGetPinnedEventsPartial() {
			var user = await _userManager.GetUserAsync(User);
            PageData = new(_eventManager);

            var success = PageData.LoadPinnedEvents(user);

            if (!success) return new PartialViewResult();

            return Partial("_PinnedEvents",PageData.PinnedEvents);
        }
		public async Task<IActionResult> OnPostAddPoll(long eventID,string returnUrl) {
            var user =_userManager.GetUserId(User);
            var ue = await _eventManager.GetUserEventAsync(eventID,user);
            if (ue != null && ue.IsCreator) {
                await _eventManager.CreatePollAsync(ue);
				await _eventManager.SaveAsync();
			}
			return Redirect(returnUrl);
		}
		public async Task<IActionResult> OnPostAddPollGame(string gameName,long pollID,string returnUrl) {
            if (gameName == "Enter Game Name" || gameName == "") {
                return Redirect(returnUrl);
            }
            LetsGame_PollOption po = new(gameName);
            _eventManager.AddPollOption(pollID, po);
			await _eventManager.SaveAsync();
			return Redirect(returnUrl);
		}
        public async Task<IActionResult> OnPostCastVote(string returnURL, long pollID, long pollOptionID) {
            var user = _userManager.GetUserId(User);
            if (string.IsNullOrEmpty(user)) return BadRequest();
 
            if(_eventManager.AddUserPollVote(user,pollID,pollOptionID)) await _eventManager.SaveAsync();
            return Redirect(returnURL);
            
        }
        public async Task<IActionResult> OnPostCastVoteAjax(long pollID, long pollOptionID) {

            var user = _userManager.GetUserId(User);

            if (string.IsNullOrEmpty(user)) return BadRequest();

            if (!_eventManager.AddUserPollVote(user,pollID,pollOptionID)) {
                return BadRequest();
            }

            await _eventManager.SaveAsync();
			return StatusCode(200);
        }
		public async Task<PartialViewResult> OnGetPollPartial(long pollID) {
			var user = await _userManager.GetUserAsync(User);

            PageData = new UserEventsData(_eventManager);
            var success = await PageData.LoadPoll(user, pollID, Request.Path);

            if (!success) return new PartialViewResult();

			return Partial("_Poll",PageData.Poll);
		}
        public async Task<PartialViewResult> OnGetSearchPartial(string input, long eventID) {
			var user = await _userManager.GetUserAsync(User);

			return Partial("_UserSearchResults",GetPossibleUsers(user, input, eventID));
        }
		public List<FriendData> GetPossibleUsers(LetsGame_User user, string input, long eventID) {


            if (input == null) input = string.Empty;
			//Gets a list of ID's for users that are already in a relationship with the current user.
			//Used to cross reference generated list and avoid adding a friend twice.
			var currentParticipants = _eventManager.GetUserEvent(eventID,user.Id).Event.Participants.Select(r => r.Id);
            
			//create list of possible users to befriend
			List<FriendData> users = _friendsManager.GetAllFriends(user)
				.Where(f => f.Username.ToUpper().StartsWith(input.ToUpper())
							&& f.ID != user.Id
							&& !ContainsID(currentParticipants,f.ID)
                            && !_eventManager.HasInvite(eventID, f.ID))
				.Select(u => u).ToList();

			return users;
		}
        public bool ContainsID(IEnumerable<string>? e, string id) {
            if (e == null) return false;
            return e.Contains(id);
        }
        public async Task<IActionResult> OnPostEventInvite(string friendID, long eventID) {

            var success = _eventManager.InviteFriend(eventID,friendID);

            if (success) {
               StatusMessage = "Success: Invite";
            }
            return Redirect($"{eventID}");
        }

        public async Task<IActionResult> OnPostLeaveEvent(long eventID) {
            var user = await _userManager.GetUserAsync(User);
            await _eventManager.LeaveEventAsync(eventID,user.Id);
            await _eventManager.SaveAsync();
            return Redirect("/Hub/Events");
        }

		public async Task<PartialViewResult> OnGetSearchResultPartial(string input,long eventID) {
			var user = await _userManager.GetUserAsync(User);
			return Partial("_UserSearchResults",GetPossibleUsers(user,input,eventID));
		}
	}
}

Areas/Hub/Pages/Events/Edit.cshtml
@page "{eventID:int?}"
@model LetsGame.Areas.Hub.Pages.Events.EditModel
@{
	ViewData["Title"] = "Create Event";
}

<partial name="_StatusMessage" model="Model.StatusMessage" />

<div class="row">
	<div class="col-md-6">
		@if (Model.IsCreate){
			<h1>Create a new Event</h1>
			<h3 class="lead">Fill in the following fields to create a new event.</h3>
		} else {
			<h1>Event Settings</h1>
		}
		<form method="post" asp-route-isCreate="@Model.IsCreate" asp-route-returnUrl="@Model.ReturnURL">
			<div class="mb-3 form-floating">
				<input asp-for="Event.EventName" placeholder="@Model.Event.EventName" class="form-control" />
				<label asp-for="Event.EventName" class="form-label">Event Name</label>
			</div>

			<div class="mb-3 form-floating">
				<textarea asp-for="Event.Description" class="form-control" style="min-height:8rem;"></textarea>
				<label asp-for="Event.Description" class="form-label">Event Description</label>
				<span asp-validation-for="Event.Description" class="text-danger"></span>
			</div>
			<div class="mb-3 form-floating">
				<input asp-for="Event.EventDateTime" class="form-control" />
				<label asp-for="Event.EventDateTime" placeholder="@Model.Event.EventDateTime" class=" form-label">Event Date</label>
				<span asp-validation-for="Event.EventDateTime" class="text-danger"></span>
			</div>
			<div class="mb-3 form-floating">
				<input asp-for="Event.Location" placeholder="@Model.Event.Location" class=" form-control" />
				<label asp-for="Event.Location" class="form-label">Event Location</label>
			</div>
			<input type="hidden" asp-for="Event.ID" />
			<input type="hidden" asp-for="Event.Poll" />
			<div class="d-flex">
				<button type="submit" class="btn btn-primary me-2">@(Model.IsCreate ? "Create" : "Save")</button>
				<button type="submit" asp-page-handler="Cancel" asp-route-returnUrl="@Model.ReturnURL" class="btn btn-secondary">Cancel</button>
			</div>
		</form>
	</div>
</div>

Areas/Hub/Pages/Events/Index.cshtml
@page "{eventID:long?}"
@using LetsGame.Data.Models;
@using LetsGame.Areas.Identity.Data;
@using LetsGame.Areas.Hub.Models;
@using LetsGame.Areas.Hub.Models.Controls;
@using System.Globalization;
@model LetsGame.Areas.Hub.Pages.EventModel
@{
	ViewData["Title"] = @Model.EventName;
}

<div class="row pt-1 pb-3">
	<h1 class="col">@Model.EventName</h1>
</div>
<partial name="_StatusMessage" model="Model.StatusMessage" />


<!--A partial for rendering a list of events consitantly-->
@if (!Model.PageData.IsValid) {
	//this model is not valid when there is neither a single event nor event list to display
	//In this case we will notify the user that they have no Events and offer them the option to create a new event
	<div>
		Uh-oh, looks like you haven't made any events. Click the add event button to get started.
	</div>
	<partial name="Controls/_UpdateEvent" model="@new EventButtonModel(null, Model.PageData.SourceURL)" />
}
else if (Model.PageData.RenderType == EventPageRenderType.SINGLE) {

	//the event that we will display
	LetsGame_UserEvent ue = Model.PageData.SingleData.UserEvent;

	@if (ue != null) {
		<partial name="_SingleEvent" model="@Model.PageData.SingleData" />
	}
}
else {
	if (Model.PageData.HasPinnedEvents) {
		<div id="pinned-events" class="row py-3">
			<partial name="_PinnedEvents" model="Model.PageData.PinnedEvents" />
		</div>
	}
	
	<partial name="_EventList" model="@Model.PageData.EventListData" />
}


@{
	//be inspired by github ui
}